### ISSUE TITLE
Moving items out of inventory doesn't work

### ISSUE THREAD

**Issue by sternschnaube** [ColdLavaLamp/extrainventory#1]
The issue was already mentioned on CurseForge, but it got still ignored.

Dropping items with keybind works, but trying to move them out of inventory doesn't.

**Comment by BaccarWozat** [comment]
I must also report that shift-clicking items won't move them into chest inventories. Furthermore, the extra two rows of inventory don't show up when you open a chest-- how are the items in them to be moved?
